name: Build and Deploy Spring Service

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-2
  ECR_REPO: springservice
  APP_DIR: /home/ec2-user/spring

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 1. Checkout
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # 2. AWS Auth
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------------
      # 3. Setup Docker Buildx
      # -------------------------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------------------------------
      # 4. Login to ECR
      # -------------------------------
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------------------------------
      # 5. Set dynamic image tag (SHA)
      # -------------------------------
      - name: Set Image URI
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # -------------------------------
      # 6. Build & Push (NO CACHE)
      # -------------------------------
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_URI \
            --push .

      # -------------------------------
      # 7. Deploy via SSM
      # -------------------------------
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy spring service" \
            --parameters commands="

              echo 'Logging into ECR'
              aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

              echo 'Switching directory'
              cd $APP_DIR

              echo 'Stopping old containers'
              docker-compose down --remove-orphans || true
              docker rm -f spring-api || true

              echo 'Removing Only springservice images'
              docker images | grep springservice | awk '{print \$3}' | xargs -r docker rmi -f

              echo 'Pulling latest image'
              docker pull $IMAGE_URI

              echo 'Starting new container'
              IMAGE_TAG=${IMAGE_TAG} docker-compose up -d --force-recreate

              echo 'Running containers'
              docker ps

              echo 'Spring images'
              docker images | grep springservice
            "
